name: calinfabri
favicon: null
layout_spectrum: 0.52545
typography_spectrum: 0.19264
title: Calin Fabri Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5eb4a9'
    - '#fabe7f'
    - '#fcfcfb'
    - '#ce7727'
    - '#570700'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
