name: calinfabri
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03181090694852173
title: Calin Fabri Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5340484143234789
purpose: []
