name: calinfabri
favicon: null
layout_spectrum: 0.5144209158606827
typography_spectrum: 0.03181090694852173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21235077735036612
  lightness: 0.12160241161473095
  saturation: 0.0064988029189407825
  rhythmicContrast: 0.5340484143234789
purpose: []
